# Generated by Django 4.1.1 on 2022-09-28 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='description of the book', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character ISBN number', max_length=13, verbose_name='ISBN')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('book_rent', models.IntegerField()),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_copies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RentalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_hours', models.FloatField(default=0)),
                ('issue_date', models.TimeField(auto_now_add=True)),
                ('return_date', models.TimeField(auto_now=True)),
                ('penalty', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_name', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
