# Generated by Django 4.1.1 on 2022-09-30 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentaldetail',
            old_name='issue_date',
            new_name='issue_time',
        ),
        migrations.RenameField(
            model_name='rentaldetail',
            old_name='return_date',
            new_name='return_time',
        ),
        migrations.RenameField(
            model_name='rentaldetail',
            old_name='penalty',
            new_name='total_rent',
        ),
        migrations.AlterField(
            model_name='rentaldetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
