# Generated by Django 4.1.1 on 2022-09-30 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_issue_date_rentaldetail_issue_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldetail',
            name='return_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
