# Generated by Django 4.1.1 on 2022-10-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_rentaldetail_return_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldetail',
            name='return_time',
            field=models.TimeField(null=True),
        ),
    ]
