# Generated by Django 4.1.1 on 2022-10-04 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_alter_rentaldetail_return_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rented_users',
            field=models.ManyToManyField(related_name='rented_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
