# Generated by Django 4.1.1 on 2022-10-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_rented_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldetail',
            name='issue_time',
            field=models.TimeField(),
        ),
    ]
